/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    static List<Map<String, Object>> files = new ArrayList<>();

    @BeforeAll
    public static void loadData() throws IOException {
        String jsonDir = Paths.get("").toAbsolutePath() + "/src/test/resources/jsonFiles";
        files.add(DataGetter.getData(jsonDir + "/file1.json"));
        files.add(DataGetter.getData(jsonDir + "/file2.json"));

        files.add(DataGetter.getData(jsonDir + "/file3.json"));
        files.add(DataGetter.getData(jsonDir + "/file4.json"));
    }

    @Test
    public void testFlatten() {
        String actual1 = Differ.generate(files.get(0), files.get(1));
        String expected1 = """
                {
                  - follow: false
                    host: hexlet.io
                  - proxy: 123.234.53.22
                  - timeout: 50
                  + timeout: 20
                  + verbose: true
                }""";

        assertEquals(expected1, actual1);

        String actual2 = Differ.generate(files.get(0), files.get(2));
        String expected2 = """
                {
                  + based: hexlet.io
                  + child: false
                  + cringe: 50
                  - follow: false
                  - host: hexlet.io
                  + parent: 123.234.53.22
                  - proxy: 123.234.53.22
                  - timeout: 50
                }""";

        assertEquals(expected2, actual2);

        String actual3 = Differ.generate(files.get(2), files.get(3));
        String expected3 = """
                {
                  - based: hexlet.io
                  + based: yes
                  - child: false
                  + child: yes
                  - cringe: 50
                  + cringe: -50
                  - parent: 123.234.53.22
                  + parent: no
                }""";

        assertEquals(expected3, actual3);
    }
}
